import monstera from "../../public/images/flowers/monstera.jpeg";
import lyrata from "../../public/images/flowers/lyrata.jpeg";
import pothos from "../../public/images/flowers/pothos.jpeg";
import succulent from "../../public/images/flowers/succulent.jpeg";
import olivier from "../../public/images/flowers/olivier.jpeg";
import basil from "../../public/images/flowers/basil.jpeg";
import calathea from "../../public/images/flowers/calathea.jpeg";
import cactus from "../../public/images/flowers/cactus.jpeg";

export const products = [
  {
    name: "haze",
    category: "fleur",
    id: "1ed",
    bestSale: true,
    light: 2,
    water: 3,
    cover: monstera,
    price: 15,
    width: 100,
    height: 100,
    rating: 4.5,
  },
  {
    name: "skunk",
    category: "fleur",
    id: "2ab",
    light: 3,
    water: 1,
    cover: lyrata,
    price: 16,
    width: 100,
    height: 100,
    rating: 4,
  },

  {
    name: "purple dream",
    category: "fleur",
    id: "3sd",
    light: 1,
    water: 2,
    cover: pothos,
    price: 9,
    width: 100,
    height: 100,
    rating: 4,
  },
    {
    name: "pinapple",
    category: "fleur",
    id: "4sd",
    light: 1,
    water: 2,
    cover: pothos,
    price: 9,
    width: 100,
    height: 100,
    rating: 4,
  },
      {
    name: "kush",
    category: "fleur",
    id: "4sd",
    light: 1,
    water: 2,
    cover: pothos,
    price: 9,
    width: 100,
    height: 100,
    rating: 4,
  },
  {
    name: "ketama",
    category: "résine",
    id: "4kk",
    light: 2,
    water: 3,
    cover: calathea,
    price: 20,
    width: 100,
    height: 100,
    rating: 5,
  },
  {
    name: "3x filtré",
    category: "résine",
    id: "5pl",
    light: 3,
    water: 1,
    cover: olivier,
    price: 25,
    width: 100,
    height: 100,
    rating: 4,
  },

  {
    name: "jaune",
    category: "résine",
    id: "8fp",
    light: 2,
    water: 1,
    cover: cactus,
    price: 6,
    width: 100,
    height: 100,
    rating: 4,
  },
   {
    name: "beldia",
    category: "résine",
    id: "9fp",
    light: 2,
    water: 1,
    cover: cactus,
    price: 6,
    width: 100,
    height: 100,
    rating: 4,
  },
    {
    name: "icolator",
    category: "résine",
    id: "9fp",
    light: 2,
    water: 1,
    cover: cactus,
    price: 6,
    width: 100,
    height: 100,
    rating: 4,
  },
  
  {
    name: "huile full spectrum",
    category: "huile",
    id: "7ie",
    bestSale: true,
    light: 2,
    water: 3,
    cover: basil,
    price: 5,
    width: 100,
    height: 100,
    rating: 2,
  },
  {
    name: "huile ya zebi",
    category: "huile",
    id: "9vn",
    light: 2,
    water: 1,
    cover: succulent,
    price: 8,
    width: 100,
    height: 100,
    rating: 3,
  },
  
    {
    name: "huile 900mg",
    category: "huile",
    id: "9vn",
    light: 2,
    water: 1,
    cover: succulent,
    price: 8,
    width: 100,
    height: 100,
    rating: 3,
  },
     {
    name: "huile 1000mg",
    category: "huile",
    id: "9vn",
    light: 2,
    water: 1,
    cover: succulent,
    price: 8,
    width: 100,
    height: 100,
    rating: 3,
  },
     {
    name: "huile 30000mg",
    category: "huile",
    id: "9vn",
    light: 2,
    water: 1,
    cover: succulent,
    price: 8,
    width: 100,
    height: 100,
    rating: 3,
  },

];
