
export const products = [
  {
    name: "haze",
    category: "fleur",
    id: "1ed",
    bestSale: true,
    light: 2,
    water: 3,
    cover: "https://i.ibb.co/T2SZnz1/purple-haze-cbd.webp",
    price: 15,
    width: 100,
    height: 100,
    rating: 4.5,
  },
  {
    name: "skunk",
    category: "fleur",
    id: "2ab",
    light: 3,
    water: 1,
    cover: "https://i.ibb.co/nzc3q4Q/fleur-cbd-super-skunk.webp",
    price: 16,
    width: 100,
    height: 100,
    rating: 4,
  },

  {
    name: "Purple dream",
    category: "fleur",
    id: "3sd",
    light: 1,
    water: 2,
    cover: "https://i.ibb.co/pypx1Yj/purpledream0610.jpg",
    price: 9,
    width: 100,
    height: 100,
    rating: 4,
    description:
      "La Purple Dream est une fleur de CBD exceptionnelle qui associe les délices gustatifs du CBD (cannabidiol) aux propriétés relaxantes de la variété de cannabis indica. Elle se caractérise par sa couleur violette profonde, son arôme enivrant aux notes florales et son goût riche et complexe mêlant saveurs terreuses, boisées et fruits rouges. Cette variété est spécialement cultivée pour son taux élevé de CBD, offrant une relaxation profonde sans effets psychoactifs. Elle peut être consommée de diverses manières, mais consultez toujours un professionnel de la santé avant usage, et respectez les lois locales sur le CBD.",
    inStock: true,
    reviews: [
      {
        id: "6499b4887402b0efd394d8f3",
        userId: "6499b184b0e9a8c8709821d3",
        productId: "3sd",
        rating: 4,
        comment:
          "good enough. I like the camera and casing. the delivery was fast too.",
        createdDate: "2023-06-26T15:53:44.483Z",
        user: {
          id: "6499b184b0e9a8c8709821d3",
          name: "Chaoo",
          email: "example1@gmail.com",
          emailVerified: null,
          image:
            "https://lh3.googleusercontent.com/a/AAcHTtcuRLwWi1vPKaQOcJlUurlhRAIIq2LgYccE8p32=s96-c",
          hashedPassword: null,
          createdAt: "2023-06-26T15:40:52.558Z",
          updatedAt: "2023-06-26T15:40:52.558Z",
          role: "USER",
        },
      },
      {
        id: "6499a110efe4e4de451c7edc",
        userId: "6475af156bad4917456e6e1e",
        productId: "3sd",
        rating: 5,
        comment: "I really liked it!!",
        createdDate: "2023-06-26T14:30:40.998Z",
        user: {
          id: "6475af156bad4917456e6e1e",
          name: "Charles",
          email: "example@gmail.com",
          emailVerified: null,
          image:
            "https://lh3.googleusercontent.com/a/AAcHTteOiCtILLBWiAoolIW9PJH-r5825pBDl824_8LD=s96-c",
          hashedPassword: null,
          createdAt: "2023-05-30T08:08:53.979Z",
          updatedAt: "2023-05-30T08:08:53.979Z",
          role: "ADMIN",
        },
      },
    ],
  },
  {
    name: "pinapple",
    category: "fleur",
    id: "4sd",
    light: 1,
    water: 2,
    cover: "https://i.ibb.co/qBmwSft/fleur-cbd-pineapple-express.jpg",
    price: 9,
    width: 100,
    height: 100,
    rating: 4,
  },
  {
    name: "kush",
    category: "fleur",
    id: "4sd",
    light: 1,
    water: 2,
    cover: "https://i.ibb.co/fXTMWxK/bubba-kush-cbd.jpg",
    price: 9,
    width: 100,
    height: 100,
    rating: 4,
  },
  {
    name: "ketama",
    category: "résine",
    id: "4kk",
    light: 2,
    water: 3,
    cover: "https://i.ibb.co/YQ50Q3c/resine-supreme-ketama-30-nature-cbd.png",
    price: 20,
    width: 100,
    height: 100,
    rating: 5,
  },
  {
    name: "3x filtré",
    category: "résine",
    id: "5pl",
    light: 3,
    water: 1,
    cover: "https://i.ibb.co/2q4N7M0/62-cbd-triple-filtre.jpg",
    price: 25,
    width: 100,
    height: 100,
    rating: 4,
  },

  {
    name: "jaune",
    category: "résine",
    id: "8fp",
    light: 2,
    water: 1,
    cover: "https://i.ibb.co/LncNVXm/resine-cbd-le-jaune.jpg",
    price: 6,
    width: 100,
    height: 100,
    rating: 4,
  },
  {
    name: "beldia",
    category: "résine",
    id: "9fp",
    light: 2,
    water: 1,
    cover: "https://i.ibb.co/Sd934PX/beldia-resine-cbg-cbn.jpg",
    price: 6,
    width: 100,
    height: 100,
    rating: 4,
  },
  {
    name: "icolator",
    category: "résine",
    id: "9fp",
    light: 2,
    water: 1,
    cover: "https://i.ibb.co/F46h590/resine-cbd-ice-o-lator-40.jpg",
    price: 6,
    width: 100,
    height: 100,
    rating: 4,
  },

  {
    name: "huile full spectrum 50%",
    category: "huile",
    id: "7ie",
    bestSale: true,
    light: 2,
    water: 3,
    cover:
      "https://i.ibb.co/HBRjCyZ/huile-de-cbd-5-a-50-full-spectrum-harvest-laboratoires.webp",
    price: 5,
    width: 100,
    height: 100,
    rating: 2,
  },
  {
    name: "huile cookie 40%",
    category: "huile",
    id: "9vn",
    light: 2,
    water: 1,
    cover: "https://i.ibb.co/PGhdRvq/Huile-40-CBD-Cookie.webp",
    price: 8,
    width: 100,
    height: 100,
    rating: 3,
  },

  {
    name: "huile 3000mg",
    category: "huile",
    id: "9vn",
    light: 2,
    water: 1,
    cover:
      "https://i.ibb.co/hLKPMvg/huile-cbd-30-3000mg-stilla-full-spectrum.webp",
    price: 8,
    width: 100,
    height: 100,
    rating: 3,
  },
  {
    name: "huile 1000mg 10%",
    category: "huile",
    id: "9vn",
    light: 2,
    water: 1,
    cover:
      "https://i.ibb.co/QY9kG4f/Huile-CBD-10-Granions-flacon-pipette-de-10ml-37601552151.jpg",
    price: 8,
    width: 100,
    height: 100,
    rating: 3,
  },
  {
    name: "huile 20%",
    category: "huile",
    id: "9vn",
    light: 2,
    water: 1,
    cover:
      "https://i.ibb.co/YQ09KhR/Huile-CBD-20-Granions-flacon-pipette-de-10ml-37601552151.jpg",
    price: 8,
    width: 100,
    height: 100,
    rating: 3,
  },
];
