import  Navbar  from "./components/navbar/Navbar"
import {Nunito} from "next/font/google"
import './globals.css'
import Banner from "./components/home/Banner"
import Fleurs from "./components/home/Fleurs"
import Resine from "./components/home/Resine"
import Huile from "./components/home/Huile"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
          <Banner/>
        <Fleurs/>
        <Resine/>
        <Huile/>
        
        </body>
    </html>
  )
}
